export const INCREMENT='INCREMENT';
export const DECREMENT='DECREMENT';
export const INCREMENT5='INCREMENT5';
export const DECREMENT5='DECREMENT5';
export const STORE_RESULTS='STORE_RESULTS';
export const DELETE_RESULTS='DELETE_RESULTS';

